### ISSUE TITLE
Error: Cannot find module '../node_modules/acl/lib/contract'

### ISSUE THREAD

**Issue by ayox** [nharris85/node_acl_arangodb#1]
I get this error .. can you help please ?

```
module.js:341
    throw err;
    ^

Error: Cannot find module '../node_modules/acl/lib/contract'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/myuser/myproject/node_modules/acl-arangodb/lib/arangodb-backend.js:7:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Function.arangodbBackend (/Users/myuser/myproject/node_modules/acl-arangodb/index.js:4:12)
    at Object.<anonymous> (/Users/myuser/myproject/services/database.js:8:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by nikordaris** [comment]
I think the issue is my assumption of the location of the node_modules. I'm not sure why I'm doing a relative path instead of just 'acl/lib/contract'. I'll take a look at it after work today

**Comment by ayox** [comment]
Hi , I changed the path of contract to : `../../acl/lib/contract` and it worked. You can try it in your end. I also submitted a commit for that. Thanks

**Comment by nikordaris** [comment]
@ayox that path only works when this is installed as another module. It will fail the tests internally. Does 'acl/lib/contract' not work for you? I created a branch that should fix this issue for you using 'acl/lib/contract' instead of the relative path. Let me know if this works for you and I'll merge it into master and push out another release to npm.

**Comment by ayox** [comment]
'acl/lib/contract' works fine for me. Thanks
